[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e8eaed"
textColor = "#31333F"
font = "sans serif"
